web-app:
  image: web-app:0.0.1-SNAPSHOT
  ports:
   - "9000:9000"
  links:
   - elasticsearch
elasticsearch:
  image: elasticsearch:1.5.2
  ports:
   - "9200:9200"
   - "9300:9300"
  volumes:
    - ./services/elasticsearch/config:/usr/share/elasticsearch/config
